/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;


/**
 *
 * @author marcosisaacarayaabarca
 */
public class VentanaPruebaPrin1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrin
     */
    public VentanaPruebaPrin1() {
        initComponents();
        initStyles();
        SetDate();
        initContent();
        PanelBienvenida p1 = new PanelBienvenida();
        //PanelUsuario p1 = new PanelUsuario();
        ShowPanel(p1);
    }
    
    public void SetDate() {
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", 
                  "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        String fecha = "Hoy es: " + dia + " de " + meses[month - 1] + " de " + year;
        Fecha1.setText(fecha);
    }
    
    public void initContent(){
        //ShowJPanel(new Registro());
       
    }
    /*
    private void ShowJPanel(JPanel tx){
    //VentanaTexto tx = new VentanaTexto();
    tx.setSize(500,300);
    tx.setLocation(0,0);
    
    Desarrollo.removeAll();
    Desarrollo.add(tx, BorderLayout.CENTER);
    Desarrollo.revalidate();
    Desarrollo.repaint();
    }*/
   
     private void ShowPanel(JPanel p){
        p.setSize(1200, 722);
        p.setLocation(0, 0);
        Desarrollo.removeAll();
        Desarrollo.add(p, BorderLayout.CENTER );
        //content.setViewportView(p);//ESTE ES PARA SCROLLPANEL
        Desarrollo.revalidate();
        Desarrollo.repaint();
 }
    
    //configuracion estilos letras
    private void initStyles(){
        Mensaje_Bienvenida.putClientProperty("FlatLaf.style", "font: 200% $light.font");
        Mensaje_Bienvenida.setForeground(Color.DARK_GRAY);
        mensaje1.putClientProperty( "FlatLaf.style", "font: bold $h00.regular.font" );
        mensaje1.setForeground(Color.white);
        mensaje2.putClientProperty("FlatLaf.style", "font: bold $h0.regular.font");
        mensaje2.setForeground(Color.white);
        //Fecha1.putClientProperty("FlatLaf.style", "font: bold 24 $light.font");
        //Fecha1.setForeground(Color.white);
        appnombre.putClientProperty("FlatLaf.style", "font: bold $h0.regular.font");
        appnombre.setForeground(Color.white);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabezado = new javax.swing.JPanel();
        mensaje1 = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        Mensaje_Bienvenida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Menu = new javax.swing.JPanel();
        appnombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Principal = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        Registro = new javax.swing.JButton();
        Medicion = new javax.swing.JButton();
        Ejercicio = new javax.swing.JButton();
        Salida = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Desarrollo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 537));

        Encabezado.setBackground(new java.awt.Color(51, 153, 255));
        Encabezado.setPreferredSize(new java.awt.Dimension(750, 150));

        mensaje1.setBackground(new java.awt.Color(51, 51, 51));
        mensaje1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        mensaje1.setForeground(new java.awt.Color(0, 0, 0));
        mensaje1.setText("Sistema del Gimnasio");

        mensaje2.setFont(new java.awt.Font("Didot", 2, 18)); // NOI18N
        mensaje2.setForeground(new java.awt.Color(0, 0, 0));
        mensaje2.setText("Fecha:  ");

        Fecha1.setFont(new java.awt.Font("Gujarati MT", 2, 24)); // NOI18N
        Fecha1.setText("jLabel1");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addComponent(mensaje1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addGap(276, 276, 276))
                    .addGroup(EncabezadoLayout.createSequentialGroup()
                        .addComponent(mensaje2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Mensaje_Bienvenida.setFont(new java.awt.Font("Devanagari MT", 1, 18)); // NOI18N
        Mensaje_Bienvenida.setText("BIENVENIDOS A POWERLAB");
        Mensaje_Bienvenida.setToolTipText("");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        Menu.setBackground(new java.awt.Color(0, 102, 255));
        Menu.setPreferredSize(new java.awt.Dimension(270, 640));

        appnombre.setFont(new java.awt.Font("Devanagari MT", 3, 24)); // NOI18N
        appnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appnombre.setText("POWERLAB");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(0.9F);
        jSeparator1.setAlignmentY(0.9F);

        Principal.setBackground(new java.awt.Color(51, 51, 255));
        Principal.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Principal.setForeground(new java.awt.Color(255, 255, 255));
        Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/home-outline.png"))); // NOI18N
        Principal.setText("Principal");
        Principal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principal.setBorderPainted(false);
        Principal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Principal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principal.setIconTextGap(10);
        Principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrincipalActionPerformed(evt);
            }
        });

        Usuario.setBackground(new java.awt.Color(51, 51, 255));
        Usuario.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user_icon_150670.png"))); // NOI18N
        Usuario.setText("Usuario");
        Usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Usuario.setBorderPainted(false);
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Usuario.setIconTextGap(10);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Registro.setBackground(new java.awt.Color(51, 51, 255));
        Registro.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/registroico.jpg"))); // NOI18N
        Registro.setText("Registros");
        Registro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Registro.setBorderPainted(false);
        Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Registro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Registro.setIconTextGap(10);
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });

        Medicion.setBackground(new java.awt.Color(51, 51, 255));
        Medicion.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Medicion.setForeground(new java.awt.Color(255, 255, 255));
        Medicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/waist_measurement_icon_224826.png"))); // NOI18N
        Medicion.setText("Medicion");
        Medicion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Medicion.setBorderPainted(false);
        Medicion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Medicion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Medicion.setIconTextGap(10);
        Medicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicionActionPerformed(evt);
            }
        });

        Ejercicio.setBackground(new java.awt.Color(51, 51, 255));
        Ejercicio.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Ejercicio.setForeground(new java.awt.Color(255, 255, 255));
        Ejercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ejercicioico.jpg"))); // NOI18N
        Ejercicio.setText("Ejercicio");
        Ejercicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Ejercicio.setBorderPainted(false);
        Ejercicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ejercicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Ejercicio.setIconTextGap(10);
        Ejercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjercicioActionPerformed(evt);
            }
        });

        Salida.setBackground(new java.awt.Color(51, 51, 255));
        Salida.setFont(new java.awt.Font("Silom", 0, 14)); // NOI18N
        Salida.setForeground(new java.awt.Color(255, 255, 255));
        Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salirico.jpg"))); // NOI18N
        Salida.setText("Salir");
        Salida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Salida.setBorderPainted(false);
        Salida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Salida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Salida.setIconTextGap(10);
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Medicion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ejercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(appnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(appnombre)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Medicion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Ejercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(Menu);

        Desarrollo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DesarrolloLayout = new javax.swing.GroupLayout(Desarrollo);
        Desarrollo.setLayout(DesarrolloLayout);
        DesarrolloLayout.setHorizontalGroup(
            DesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        DesarrolloLayout.setVerticalGroup(
            DesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(Desarrollo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mensaje_Bienvenida)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Mensaje_Bienvenida)
                .addGap(10, 10, 10)
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        PanelUsuario p1 = new PanelUsuario();
        ShowPanel(p1);
    }//GEN-LAST:event_UsuarioActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        //PanelRegistro p1 = new PanelRegistro();
        //ShowPanel(p1);
    }//GEN-LAST:event_RegistroActionPerformed

    private void EjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjercicioActionPerformed
        PanelEjercicio p1 = new PanelEjercicio();
        ShowPanel(p1);
    }//GEN-LAST:event_EjercicioActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalidaActionPerformed

    private void MedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicionActionPerformed
        PanelMedicion p1 = new PanelMedicion();
        ShowPanel(p1);
    }//GEN-LAST:event_MedicionActionPerformed

    private void PrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrincipalActionPerformed
        PanelBienvenida p1 = new PanelBienvenida();
        ShowPanel(p1);
    }//GEN-LAST:event_PrincipalActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaPrin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaPrin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaPrin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPruebaPrin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPruebaPrin1().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desarrollo;
    private javax.swing.JButton Ejercicio;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JButton Medicion;
    private javax.swing.JLabel Mensaje_Bienvenida;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Principal;
    private javax.swing.JButton Registro;
    private javax.swing.JButton Salida;
    private javax.swing.JButton Usuario;
    private javax.swing.JLabel appnombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    // End of variables declaration//GEN-END:variables


}
