/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import Controlador.Controlador_ClaseGrupal;
import Controlador.Controlador_Cliente;
import Controlador.Controlador_Instructor;


/**
 *
 * @author marcosisaacarayaabarca
 */
public class PanelPrincipalClaseGrupal extends javax.swing.JPanel {

    private Controlador_ClaseGrupal controlador;
    private Controlador_Instructor controladorInstructor;
    private Controlador_Cliente controladorCliente;
    
    /**
     * Creates new form PanelRegistro
     */
    public PanelPrincipalClaseGrupal(Controlador_ClaseGrupal controlador, Controlador_Instructor controladorInstructor, Controlador_Cliente controladorCliente) {
    initComponents();
    this.controlador = controlador;
    this.controladorInstructor = controladorInstructor;
    this.controladorCliente = controladorCliente;
}


    private void ShowPanel(JPanel p) {
        p.setSize(600, 600);
        p.setLocation(0, 0);
        MostrarClaseGrupal.removeAll();
        MostrarClaseGrupal.setLayout(new BorderLayout());
        MostrarClaseGrupal.add(p, BorderLayout.CENTER); 
        MostrarClaseGrupal.revalidate();
        MostrarClaseGrupal.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        MostrarClaseGrupal = new javax.swing.JPanel();
        txtCrearClaseGrupal = new javax.swing.JLabel();
        btnCrearClaseGrupal = new javax.swing.JButton();
        txtMatricularCliente = new javax.swing.JLabel();
        btnMatricular = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/WhatsApp Image 2025-09-10 at 2.09.22 PM.jpeg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(765, 404));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -330, 247, 1253));

        jLabel2.setFont(new java.awt.Font("DIN Condensed", 2, 48)); // NOI18N
        jLabel2.setText("CLASE GRUPALES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 17, 300, 68));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 73, 519, -1));

        jScrollPane1.setViewportView(MostrarClaseGrupal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 610, 400));

        txtCrearClaseGrupal.setText("Crear Clases Grupales");
        jPanel1.add(txtCrearClaseGrupal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 140, 20));

        btnCrearClaseGrupal.setText("Crear");
        btnCrearClaseGrupal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClaseGrupalActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearClaseGrupal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        txtMatricularCliente.setText("Matricular Clientes");
        jPanel1.add(txtMatricularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));

        btnMatricular.setText("Matricular");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        jPanel1.add(btnMatricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1560, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearClaseGrupalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClaseGrupalActionPerformed
        PanelCrearClaseGrupal p1 = new PanelCrearClaseGrupal(this.controlador, this.controladorInstructor, this.controladorCliente);

        ShowPanel(p1);
    }//GEN-LAST:event_btnCrearClaseGrupalActionPerformed

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
       PanelMatricularClaseGrupal p1 = new PanelMatricularClaseGrupal(this.controlador, this.controladorCliente, this.controladorInstructor);
        ShowPanel(p1);
    }//GEN-LAST:event_btnMatricularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MostrarClaseGrupal;
    private javax.swing.JButton btnCrearClaseGrupal;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtCrearClaseGrupal;
    private javax.swing.JLabel txtMatricularCliente;
    // End of variables declaration//GEN-END:variables
}
