/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import Controlador.Controlador_Cliente;
import Controlador.Controlador_Medicion;
import Controlador.Controlador_Sucursal;

//import Vista.PanelPruebaMedicion;


/**
 *
 * @author marcosisaacarayaabarca
 */
public class PanelMedicion extends javax.swing.JPanel {

    private Controlador_Medicion controladorMedicion;
    private Controlador_Cliente controladorCliente;
    private Controlador_Sucursal controladorSucursal; 

    /**
     * Creates new form PanelRegistro
     */
    
     public PanelMedicion(Controlador_Medicion controladorMedicion, Controlador_Cliente controladorCliente, Controlador_Sucursal controladorSucursal) {
               initComponents();

         this.controladorMedicion = controladorMedicion;
        this.controladorCliente = controladorCliente;
                this.controladorSucursal = controladorSucursal; 

    }
 
   private void ShowPanel(JPanel p) {
    p.setSize(jPanel2.getWidth(), jPanel2.getHeight());
    p.setLocation(0, 0);

    jPanel2.removeAll();
    jPanel2.setLayout(new BorderLayout());
    jPanel2.add(p, BorderLayout.CENTER);

    jPanel2.revalidate();
    jPanel2.repaint();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnReporteMedicion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPruebaIMC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnReportexSucursal = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/WhatsApp Image 2025-09-10 at 2.09.22 PM.jpeg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(765, 404));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -330, 247, 1253));

        jLabel2.setFont(new java.awt.Font("DIN Condensed", 2, 48)); // NOI18N
        jLabel2.setText("MEDICION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 17, 290, 68));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 73, 519, -1));

        btnReporteMedicion.setText("Buscar");
        btnReporteMedicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteMedicionActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteMedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel5.setText("Reporte Medicion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 20));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 590, 440));

        jLabel6.setText("Realizar Prueba IMC:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 20));

        btnPruebaIMC.setText("Buscar");
        btnPruebaIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaIMCActionPerformed(evt);
            }
        });
        jPanel1.add(btnPruebaIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel4.setText("Reporte IMC Sucursal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        btnReportexSucursal.setText("Reporte");
        btnReportexSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportexSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportexSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteMedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMedicionActionPerformed
        PanelReporteMedicion p1 = new PanelReporteMedicion(this.controladorMedicion);
        ShowPanel(p1);
    }//GEN-LAST:event_btnReporteMedicionActionPerformed

    private void btnPruebaIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaIMCActionPerformed
        PanelPruebaMedicion p1 = new PanelPruebaMedicion(this.controladorMedicion, this.controladorCliente);
        ShowPanel(p1);
    }//GEN-LAST:event_btnPruebaIMCActionPerformed

    private void btnReportexSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportexSucursalActionPerformed
        // TODO add your handling code here:
         PanelReporteIMCSucursal p1 = new PanelReporteIMCSucursal(this.controladorSucursal, this.controladorMedicion);
        ShowPanel(p1);
    }//GEN-LAST:event_btnReportexSucursalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPruebaIMC;
    private javax.swing.JButton btnReporteMedicion;
    private javax.swing.JButton btnReportexSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
