/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.ClaseGrupal;
import Modelo.Cliente;
import Controlador.Controlador_ClaseGrupal;
import Controlador.Controlador_Cliente;
import Controlador.Controlador_Instructor;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcosisaacarayaabarca
 */
public class PanelMatricularClaseGrupal extends javax.swing.JPanel {

    private Controlador_ClaseGrupal controladorClase;
    private Controlador_Cliente controladorCliente;
    private Controlador_Instructor controladorInstructor;
   
    private DefaultTableModel modeloTabla; // El modelo de la tabla

   

    
    /**
     * Creates new form PanelMatricularClaseGrupal
     */
    /*public PanelMatricularClaseGrupal(Controlador_ClaseGrupal controladorClase, Controlador_Cliente controladorCliente) {
        this.controladorClase = controladorClase;
        this.controladorCliente = controladorCliente;
        initComponents();
        cargarClases();
        cargarClientes();
        inicializarTabla();
    }*/
    public PanelMatricularClaseGrupal(Controlador_ClaseGrupal controladorClase,
                                  Controlador_Cliente controladorCliente,
                                  Controlador_Instructor controladorInstructor) {
    this.controladorClase = controladorClase;
    this.controladorCliente = controladorCliente;
    this.controladorInstructor = controladorInstructor; // agregar atributo
    initComponents();
    cargarClases();
    cargarClientes();
    inicializarTabla();
   

}
    
     private void cargarClases() {
        CombxClase.removeAllItems();
        for (ClaseGrupal c : controladorClase.listarClases()) {
            CombxClase.addItem(c);
        }
    }

    private void cargarClientes() {
        CombxCliente.removeAllItems();
        for (Cliente c : controladorCliente.listar()) {
            CombxCliente.addItem(c);
        }
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(new String[]{"Nombre", "Correo", "Teléfono"}, 0);
        Tabla.setModel(modeloTabla);  // Asignamos el modelo al JTable
    }

    /*
    private void actualizarTabla(ClaseGrupal clase) {
    modeloTabla.setRowCount(0); // Limpiar datos anteriores
    if (clase != null) {
        for (Cliente c : clase.getMatriculados()) {
            modeloTabla.addRow(new Object[]{
                c.getNombre(),
                c.getCorreo(),
                c.getNumero_Celular()
            });
        }
    }
}*/
    
    //borrar si nofuncionsa 
    private void actualizarTabla(ClaseGrupal clase) {
        modeloTabla.setRowCount(0); // Limpiar datos anteriores
        if (clase != null) {
            for (Cliente c : clase.getMatriculados()) {
                modeloTabla.addRow(new Object[]{
                    c.getNombre(),
                    c.getCorreo(),
                    c.getNumero_Celular()
                });
            }
        }
    }

    private void mostrarCuposClase(ClaseGrupal clase) {
        if (clase != null) {
            int disponibles = clase.getCupoMaximo() - clase.getMatriculados().size();
            JOptionPane.showMessageDialog(this, "Cupos disponibles: " + disponibles);
        }
    }
    //hasta aqui


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matricular = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelSeleccionarclase = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        CombxClase = new javax.swing.JComboBox<>();
        CombxCliente = new javax.swing.JComboBox<>();
        btnclientematt = new javax.swing.JButton();
        btnvervlienteenclase = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Matricular1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnverclasedecliente = new javax.swing.JButton();

        Matricular.setFont(new java.awt.Font("Devanagari MT", 0, 18)); // NOI18N
        Matricular.setText("MATRICULAR CLIENTES EN CLASES ");

        labelSeleccionarclase.setText("Seleccionar Clase:");

        labelCliente.setText("Cliente:     ");

        CombxClase.setModel(new javax.swing.DefaultComboBoxModel<ClaseGrupal>());
        CombxClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombxClaseActionPerformed(evt);
            }
        });

        CombxCliente.setModel(new DefaultComboBoxModel<Cliente>());
        CombxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombxClienteActionPerformed(evt);
            }
        });

        btnclientematt.setText("Matricular Cliente ");
        btnclientematt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientemattActionPerformed(evt);
            }
        });

        btnvervlienteenclase.setText("Ver Clientes Clase");
        btnvervlienteenclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvervlienteenclaseActionPerformed(evt);
            }
        });

        Matricular1.setFont(new java.awt.Font("Devanagari MT", 0, 18)); // NOI18N
        Matricular1.setText("CLIENTES MATRICULADOS EN CLASE SELECCIONADA  ");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btnverclasedecliente.setText("Ver Clases de Cliente ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelSeleccionarclase)
                                        .addGap(18, 18, 18)
                                        .addComponent(CombxClase, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnclientematt)
                                            .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnvervlienteenclase)
                                            .addComponent(CombxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(Matricular))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(Matricular1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnverclasedecliente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Matricular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeleccionarclase)
                    .addComponent(CombxClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente)
                    .addComponent(CombxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclientematt)
                    .addComponent(btnvervlienteenclase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Matricular1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnverclasedecliente)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnvervlienteenclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvervlienteenclaseActionPerformed
         ClaseGrupal clase = (ClaseGrupal) CombxClase.getSelectedItem();
        actualizarTabla(clase);
    }//GEN-LAST:event_btnvervlienteenclaseActionPerformed

    private void btnclientemattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientemattActionPerformed
        /*ClaseGrupal clase = (ClaseGrupal) CombxClase.getSelectedItem();
        Cliente cliente = (Cliente) CombxCliente.getSelectedItem();
        if (clase != null && cliente != null) {
            if (controladorClase.matricularCliente(clase, cliente)) {
                actualizarTabla(clase);
                JOptionPane.showMessageDialog(this, "Cliente matriculado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se puede matricular (sin cupo o ya inscrito).");
            }
        }*/
        ClaseGrupal clase = (ClaseGrupal) CombxClase.getSelectedItem();
        Cliente cliente = (Cliente) CombxCliente.getSelectedItem();

        if (clase == null || cliente == null) {
            return;
        }

        // Verificar máximo 3 clases por cliente
        if (controladorCliente.cantidadClasesMatriculadas(cliente) >= 3) {
            JOptionPane.showMessageDialog(this, "Cliente ya tiene 3 clases matriculadas.");
            return;
        }

        if (controladorClase.matricularCliente(clase, cliente)) {
            actualizarTabla(clase);
            mostrarCuposClase(clase);
            JOptionPane.showMessageDialog(this, "Cliente matriculado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se puede matricular (sin cupo o ya inscrito).");
        }
    }//GEN-LAST:event_btnclientemattActionPerformed

    private void CombxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombxClienteActionPerformed

    private void CombxClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombxClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombxClaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ClaseGrupal> CombxClase;
    private javax.swing.JComboBox<Cliente> CombxCliente;
    private javax.swing.JLabel Matricular;
    private javax.swing.JLabel Matricular1;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnclientematt;
    private javax.swing.JButton btnverclasedecliente;
    private javax.swing.JButton btnvervlienteenclase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelSeleccionarclase;
    // End of variables declaration//GEN-END:variables
}
